/* Great Lakes Observing System Regional Association 
 * @Author Guan Wang
 * @Organization Great Lakes Commission
 * @Contact Pete Giencke
 *           pgiencke@glc.org
 *           734-971-9135
 *           Eisenhower Corporate Park
 *           2805 S. Industrial Hwy, Suite 100
 */
package org.glc.glos.coastwatch;

import java.util.logging.Logger;
import java.util.Properties;
import java.util.Date;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public final class MailSender {
	public static boolean Send(String[] lines,String server,String from,String[] to,Logger log)
	{
		boolean result=false;
		Properties prop=new Properties();
		prop.put("mail.smtp.host", server);
		Session session=Session.getInstance(prop);
		InternetAddress[] tos=null;
		StringBuilder sb=null;
		try
		{
			if(lines!=null&&server!=null&&from!=null&&to!=null)
			{
				Message msg=new MimeMessage(session);
				msg.setFrom(new InternetAddress(from));
				tos=new InternetAddress[to.length];
				for(int i=0;i<to.length;++i)
					tos[i]=new InternetAddress(to[i]);
				msg.setRecipients(Message.RecipientType.TO, tos);
				msg.setSubject("Coast Wacth New Station Notification");
				msg.setSentDate(new Date());
				sb=new StringBuilder();
				sb.append("**This is an email automatically generated by the program. Please DO NOT REPLY!**");
				sb.append(ConfigManager.NEWLINE);
				sb.append(ConfigManager.NEWLINE);
				sb.append(ConfigManager.NEWLINE);
				sb.append("Please add new stations with nws_handles below:");
				sb.append(ConfigManager.NEWLINE);
				for(String tmp:lines)
				{
					sb.append(tmp);
					sb.append(ConfigManager.NEWLINE);
				}
				sb.append(ConfigManager.NEWLINE);
				sb.append(ConfigManager.NEWLINE);
				sb.append("Thank you and have a nice day!");
				msg.setText(sb.toString());
				Transport.send(msg);
				result=true;
			}
			else
			{
				if(log!=null)
					log.severe("Some of properties that SMTP mail server needs are not available in the configuration file!");
			}
		}
		catch(MessagingException me)
		{
			if(log!=null)
			{
				log.info("Sending email failed!");
				log.severe(me.getMessage());
			}
		}
		catch(Exception e)
		{
			if(log!=null)
			{
				log.info("Sending email failed!");
				log.severe(e.getMessage());
			}
		}
		return result;
	}
}
