/* Great Lakes Observing System Regional Association 
 * @Author Guan Wang
 * @Organization Great Lakes Commission
 * @Contact Pete Giencke
 *           pgiencke@glc.org
 *           734-971-9135
 *           Eisenhower Corporate Park
 *           2805 S. Industrial Hwy, Suite 100
 */
package org.glc.glos.coastwatch;

import java.util.logging.Logger;
import java.util.Properties;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.FileNotFoundException;

public class SyncUpdate {

	private String fileName=null;
	private Properties props=null;
	private Logger log=null;
	/**
	 * @param args
	 */
	public SyncUpdate(String file,Logger logger) throws IOException
	{
		fileName=file;
		log=logger;
		props=new Properties();
		File f=new File(fileName);
		//Make sure the file will be there
		f.createNewFile();
	}
	public Properties Sync(String jdbc,String url,String user,String passwd,String tableName)
	{
		try
		{
			SqlHelper sql=new SqlHelper(jdbc,url,user,passwd,log);
			sql.createUpdateMgr1(props,tableName);
		}
		catch(ClassNotFoundException cnfe)
		{
			if(log!=null)
			{
				log.info("Can not find the class for JDBC!");
				log.severe(cnfe.getMessage());
			}
		}
		return props;
		
	}
	public Properties InitStations(String jdbc,String url,String user,String passwd)
	{
		try
		{
			SqlHelper sql=new SqlHelper(jdbc,url,user,passwd,log);
			sql.initStations(props);
		}
		catch(ClassNotFoundException cnfe)
		{
			if(log!=null)
			{
				log.info("Can not find the class for JDBC!");
				log.severe(cnfe.getMessage());
			}
		}
		return props;
	}
	public int SaveFile()
	{
		int result=0;
		try
		{
			if(props!=null&&props.size()>0)
			{
				FileOutputStream fos=new FileOutputStream(fileName,false);
				props.store(fos, "Please DO NOT EDIT this file!");
				fos.flush();
				fos.close();
				result=props.size();
			}
			else
				if(log!=null)
					log.info("Didn't get any information from the database, data table 'multi_obs' is empty or possible error happened somewhere!");
			
		}
		catch(FileNotFoundException fnfe)
		{
			if(log!=null)
			{
				log.info("Can not find the file for output!");
				log.severe(fnfe.getMessage());
			}
		}
		catch(IOException ie)
		{
			if(log!=null)
			{
				log.info("Error when update the station.dat!");
				log.severe(ie.getMessage());
			}
		}
		return result;
	}
}
